# Generated by Django 3.1.4 on 2020-12-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.TextField(default='')),
                ('label_aktivitas', models.IntegerField(choices=[(0, 'Tidak Diketahui'), (1, 'Naik Motor'), (2, 'Jogging')], default=0)),
                ('locations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
