# Generated by Django 3.1.5 on 2021-01-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webKomber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='label_aktivitas',
            field=models.IntegerField(choices=[(0, 'Diam'), (1, 'Naik Motor'), (2, 'Lompat Lompat')], default=0),
        ),
    ]
